### PR TITLE
feat (models) add 3D models for the mcu v2

### LINKED ISSUE #37: Design a new case for the upgraded hardware
In #36 we want to introduce a new hardware version. Since the board dimensions changed, a new case should be designed to properly fit it.

- [x] Once the boards are there, design a new case
- [x] Make sure it can easily be 3D printed
- [x] Provide it as stl file(s)

### PR DESCRIPTION
**Pull request by TheRealKasumi**
closes #37

Created and added a new case for the mcu v.2 hardware. Any proposals for improvement? 

https://user-images.githubusercontent.com/62426919/208900290-73071565-dcb9-49e1-a1dc-fed99e0ef8b6.mp4

### CODE REVIEW

**Comment by TheRealKasumi** [comment]
I just added everyone to give feedback. Thanks to @rgrae81 for the design. What do you think? I personally like it.

**Review by JakobLichterfeld — COMMENTED** [review]
lgtm (I used [ViewSTL](https://www.viewstl.com/))
Why the split of the case and the cover in separate files?

**Comment by TheRealKasumi** [comment]
Good question. No special reason I am aware of.

**Comment by rgrae81** [comment]
> lgtm (I used [ViewSTL](https://www.viewstl.com/)) Why the split of the case and the cover in separate files?

Because it's easier to merge them in the slicer to print them together as to seperate them.
Also you can align it easier by your preferations in the slicer.

**Comment by TheRealKasumi** [comment]
We also quickly added a aio version ;) .

**Review by rgrae81 — APPROVED** [review]

**Review by danielbayerlein — DISMISSED** [review]

**Comment by JakobLichterfeld** [comment]
I would love to see some sort of explanation in build guide for the fan adapter for example, so just a one liner

**Comment by TheRealKasumi** [comment]
Added a few workds for 3D printing. The other changes... it's my formatters "fault" 😝 .

**Review by JakobLichterfeld — APPROVED** [review]

**Review by JakobLichterfeld — APPROVED** [review]
lgtm

**Comment by TheRealKasumi** [comment]
Since the others already aproved the models before, I will go ahead and merge it :) .

**Pull request merged**
