### PR TITLE
feat: add new pulse effect

### PR DESCRIPTION
**Pull request by TheRealKasumi**
This PR has no related Issue. But this morning I felt like adding a new effect. It's a pulsing effect that can either move through different colors, pulse with a user defined color or react to music.

Also brought in a few code improvements that I had laying around.

### CODE REVIEW

**Review by JakobLichterfeld — APPROVED** [review]
lgtm

**Review by danielbayerlein — APPROVED** [review]
LGTM 🚀

**Comment by danielbayerlein** [comment]
@TheRealKasumi Can you please update the `api/ReadMe.md`?

**Comment by TheRealKasumi** [comment]
Ah, I am dumb. I pushed it to internal only.

**Review by JakobLichterfeld — APPROVED** [review]
lgtm, love the AudioUnit condition :-)

**Comment by TheRealKasumi** [comment]
Tested it, all working! Thanks for the frontend contribution!

**Pull request merged**
